---
title: "Publications"
site: distill::distill_website

---


### Publications

Tran T., Philipp J., Bassi J., Nibber N., Draper J., Lin T., Palanichamy J.K., Kumar A., Paing M., King J., Katzman S, Sanford J.R., Rao D.S.: Post-transcriptional gene regulation by the RNA binding protein IGF2BP3 is critical for MLL-AF4 mediated leukemogenesis. [bioRxiv doi 10.1101/2020.12.20.423624](https://www.biorxiv.org/content/10.1101/2020.12.20.423624v2)

Dargytė M., Philipp J., Palka C., Howard J., Katzman S., Stone M., Sanford J. 2020. Splicing Factor SRSF1 expands the regulatory logic of microRNA expression. [bioRxiv doi: 10.1101/2020.05.12.092270](https://www.biorxiv.org/content/10.1101/2020.05.12.092270v1)

Wu R., Sedlmeier G., Schmaus A., Philipp J., Thiele W., Lenka K., Sleeman J.P.: Hyaluronic acid-CD44 interactions promote BMP4/7-dependent Id1/3 expression in melanoma cells, Scientific Reports, Volume 8, Article number: 14913 (2018). [doi: 10.1038/s41598-018-33337-7](https://www.nature.com/articles/s41598-018-33337-7)

### Presentations

Tran T., Bassi J., Nibber N., Philipp J., Draper J., Lin T., Palanichamy J.K., Kumar A., Paing M., King J., Katzman S, Sanford J.R., Rao D.S.: The RNA-binding protein IGF2BP3 is required in MLL-AF4 mediated leukemogenesis, presented at the 62nd ASH Annual Meeting; 2020 December 5-8; American Society of Hematology (virtual meeting due to Covid-19 pandemic, originally in San Diego, CA, US)

Cao L., Arab M., Philipp J., Hutchins E., Moss M., Tyshchenko K., Wong P., Singh S., von Kugelgen N., Lee B., Lu J., Fan J.: BiocSwirl: Interactive R Tutorials for Neuroinformatics, poster, presented at FENS Forum 2020; 2020 July 11-15; Federation of European Neuroscience Societies (virtual meeting due to Covid-19 pandemic, originally in Glasgow, Scotland)

Philipp J., Draper J., Katzman S., Salama S., Haussler D., Sanford J.: Isoform-specific translation control is conserved in primates, poster, presented at the 25th Annual Meeting of the RNA Society; 2020 May; RNA Society (virtual meeting due to Covid-19 pandemic, originally in Vancouver, Canada)

Philipp J., Draper J., Katzman S., Salama S., Haussler D., Sanford J.: Isoform-specific translation control is conserved across higher primates, talk, presented at the 24th Annual Meeting of the RNA Society; 2019 June 15; RNA Society, Kraków, Poland

### Workshops

[Interactive R and RNAseq course with BiocSwirl, CSHL DIAS, Feb 2020](https://github.com/biocswirl-dev-team/learning_resources/tree/main/CSHL_workshop)